apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  # clusterName is required and must be unique among all managed clusters
  clusterName: cluster-2	
  git:
    syncRepo: https://github.com/ashmrkvch/drivers-kuber.git
    syncBranch: master
    secretType: ssh
    policyDir: "foo-corp"
